namespace Back.Ctac.Data.Setting
{
    internal static class EvaluacionProcedure
    {
        internal const string USP_INS_GRADO_SECCION = "[evaluacion].[USP_INS_GRADO_SECCION]";
        internal const string USP_UPD_NOTA_CAMBIO_SECCION = "evaluacion.USP_UPD_NOTA_CAMBIO_SECCION";
        internal const string USP_UPD_NOTA_CAMBIO_SECCION_EBA = "evaluacion.USP_UPD_NOTA_CAMBIO_SECCION_EBA";


        internal const string USP_INS_SECCION_EVALUACION_PERIODO = "[evaluacion].[USP_INS_SECCION_EVALUACION_PERIODO]";
        internal const string USP_INS_IE_EVALUACION_PERIODO_PROMOCIONAL = "[evaluacion].[USP_INS_IE_EVALUACION_PERIODO_PROMOCIONAL]";

        internal const string USP_INS_IE_EVALUACION_PERIODO_PROMOCIONAL_PERIODO = "[evaluacion].[USP_INS_IE_EVALUACION_PERIODO_PROMOCIONAL_PERIODO]";
        internal const string USP_INS_SECCION_EVALUACION_PERIODO_PROMOCIONAL = "[evaluacion].[USP_INS_SECCION_EVALUACION_PERIODO_PROMOCIONAL]";
        internal const string USP_UPD_SECCION_EVAL_PER_PROM_HABILITAR = "[evaluacion].[USP_UPD_SECCION_EVAL_PER_PROM_HABILITAR]";

        internal const string USP_UPD_IE_EVALUACION_PERIODO_PROMOCIONAL_ESTADO = "evaluacion.USP_UPD_IE_EVALUACION_PERIODO_PROMOCIONAL_ESTADO";
        internal const string USP_DEL_SECCION_EVALUACION_PERIODO_PROMOCIONAL_BY_ID = "[evaluacion].[USP_DEL_SECCION_EVALUACION_PERIODO_PROMOCIONAL_BY_ID]";


        internal const string USP_UPD_SECCION_EVAL_PER_PROM_HABILITAR_PROCESAMIENTO = "evaluacion.USP_UPD_SECCION_EVAL_PER_PROM_HABILITAR_PROCESAMIENTO";
        internal const string USP_INS_SECCION_EVALUACION_PERIODO_EXT = "[evaluacion].[USP_INS_SECCION_EVALUACION_PERIODO_EXT]";
        internal const string USP_INS_SECCION_EVALUACION_RECTIFICACION_EXT = "[evaluacion].[USP_INS_SECCION_EVALUACION_RECTIFICACION_EXT]";



        internal const string USP_DEL_SECCION_EVALUACION_PERIODO_EXT = "[evaluacion].[USP_DEL_SECCION_EVALUACION_PERIODO_EXT]";
        internal const string USP_INS_SECCION_EVALUACION_PERIODO_PROMOCIONAL_EXT = "[evaluacion].[USP_INS_SECCION_EVALUACION_PERIODO_PROMOCIONAL_EXT]";
        internal const string USP_DEL_SECCION_EVALUACION_PERIODO_PROMOCIONAL_EXT = "[evaluacion].[USP_DEL_SECCION_EVALUACION_PERIODO_PROMOCIONAL_EXT]";
    }
}